version: '3.7'

services:

  db:
    image: mariadb:latest
    volumes:
      - ${PWD}/db/:/var/lib/mysql
      - ${PWD}/db/init/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    # expose:
    #  - 3306
    env_file: ./db/.env

  backend:
    image: python:3.7-bullseye
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/home/
    working_dir: /home
    command: bash -c "apt-get update && apt-get install vim -y && pip install --upgrade pip && pip install fastapi && pip install uvicorn && pip install pandas && pip install numpy && pip install psycopg2-binary && pip install pymysql && pip install sqlalchemy && pip install openpyxl && python db_init.py && tail -f /dev/null"
    depends_on:
      - db
  
  frontend:
    image: node:current-bullseye

    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/home/
    depends_on:
      - backend
    command: bash -c "apt-get update && apt-get install vim -y && tail -f /dev/null"
